---
- name: learning to register
  hosts: planet-express
  gather_facts: yes   # no for example: switches and routers

  tasks:
    - name: reach out and get url
      get_url:
        url: https://www.random.org/integers/?num=1&min=0&max=1&col=1&base=10&format=plain&rnd=new
        dest: ~/rand.txt   # Python doesn't like tildes, only relative or full paths
        force: yes

    - name: read a file and save the results
      command: cat ~/rand.txt
      register: readfile

    - name: you won!
      debug:
        msg: "Congrats you won! :)"
      when: readfile.stdout == "1"

    - name: you lost
      debug:
        msg: "Sorry, you lost!!!"
      when: readfile.stdout == "0"

    - name: show the contents of the file
      debug:
        var: readfile.stdout
