---
- name: Playbook that targets hosts
  hosts: planet-express
  gather_facts: yes
  vars:
    engines: chemical  # play local vars have precedence over global vars

  tasks:
  - name: Install figlet
    apt:
      name: figlet
      state: present # "present" talks to the repo for latest stable release
                     # it could be "absent" as well
    become: yes
    when: ansible_os_family == "Debian"

  - name: Install figlet
    yum:
      name: figlet
      state: present
    become: yes
    when: ansible_os_family == "RedHat"

    #  - name: Issue a command
    #    command: ls /home
    #    become: yes
    #    register: homevarz

    #  - name: display homevarz
    #    debug: # debug = print
    #      var: homevarz

    #  - name: Display the value of homevarz.stdout
    #    debug:
    #      var: homevarz.stdout

  - name: Place a redme in target systems
    copy:
            #      dest: "/home/{{homevarz.stdout}}/readme.txt"
      dest: "/home/{{inventory_hostname}}/Readme.txt"
      content: "Type figlet to enter the banner creation tool"

  - name: Display a group variable
    debug:
      var: engines
